### ISSUE TITLE
Cannot read property 'lifetimeMS' of null

### ISSUE THREAD

**Issue by Cash-Money-McCoy** [thomas-crane/nrelay#47] opened 2020-05-01 01:49 UTC
### Version info
 + nrelay version: `8.8.4`
 + RotMG version: `X33.0.1`

### Plugins
 + Realm Joiner (_unreleased_)
    + Uses features
        + GameId
    + Uses packets
        + `RandomRealm`

### Steps to reproduce
1. Start nrelay
2. Run `client.changeGameId(GameId.RandomRealm)`
3. Crash, probably when someone shoots

### Result
```
C:\Users\C\Desktop\nrelay\nrelay_v8\realm\node_modules\nrelay\lib\core\client.js:809
            const distance = projectile.lifetimeMS * (projectile.speed / 10000);
                                        ^

TypeError: Cannot read property 'lifetimeMS' of null
    at Client.onNewTick (C:\Users\C\Desktop\nrelay\nrelay_v8\realm\node_modules\nrelay\lib\core\client.js:809:41)
    at LibraryManager.callHooks (C:\Users\C\Desktop\nrelay\nrelay_v8\realm\node_modules\nrelay\lib\core\library-manager.js:215:33)
    at PacketIO.Client.io.on (C:\Users\C\Desktop\nrelay\nrelay_v8\realm\node_modules\nrelay\lib\core\client.js:94:45)
    at PacketIO.emit (events.js:198:13)
    at PacketIO.emitPacket (C:\Users\C\Desktop\nrelay\nrelay_v8\realm\node_modules\@realmlib\net\lib\packetio.js:144:18)
    at PacketIO.onData (C:\Users\C\Desktop\nrelay\nrelay_v8\realm\node_modules\@realmlib\net\lib\packetio.js:177:30)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
```

**Comment by YemelesBank** [comment] 2020-05-01 03:15
I can confirm this bug. I also had the same crash at `lib/models/projectile.js`. I'm not sure what triggers it for me, but I had it once in Guild Hall and the projectile.js one happened in a cemetery.

**Comment by thomas-crane** [comment] 2020-05-01 06:44
Thanks for reporting this guys!

The `ResourceManager`, which is responsible for this issue, is a bit of a mess. It was among the first few classes ever written for nrelay and is now several years old.

Rather than fix just this single bug, I'd like to rewrite the resource manager so the code is a bit cleaner, and in turn fix this bug.

As a result, I can't promise that this will be fixed any time soon since a rewrite is usually a non-trivial task, and I also happen to be right in the middle of exam time right now.

**Comment by iremnant** [comment] 2020-05-01 20:02
I haven't had the chance to look through the codebase thoroughly but one thing I've personally noticed is that often Objects.json contains duplicates where one contains way less info (for instance a projectile, then that exact same projectile later in the document but without LifetimeMS and such properties). I'm sure it's not that simple but I just thought why not post about it.

Troll 3 Attack 1 (cemetery boss for an example):
1st occurrence:
`{
      "type": "0x5f1f",
      "id": "Troll 3",
      "DisplayId": "Troll Matriarch",
      "Class": "Character",
      "Group": "Hallowrena",
      "Enemy": "",
      "Quest": "",
      "God": "",
      "AnimatedTexture": {
        "File": "chars16x16rEncounters",
        "Index": "84"
      },
      "HitSound": "monster/dragons_hit",
      "DeathSound": "monster/dragons_death",
      "Size": "175",
      "ShadowSize": "100",
      "MaxHitPoints": "9000",
      "Exp": "500",
      "Defense": "15",
      "StasisImmune": "",
      "Projectile": [
        {
          "id": "0",
          "ObjectId": "Troll 3 Attack 1",
          "Damage": "75",
          "Speed": "60",
          "LifetimeMS": "1500",
          "Size": "175",
          "Wavy": "",
          "ConditionEffect": {
            "_": "Hallucinating",
            "duration": "5"
          }
        },
        {
          "id": "1",
          "ObjectId": "Nature Wave",
          "Damage": "85",
          "Speed": "60",
          "LifetimeMS": "1000",
          "Size": "125",
          "ConditionEffect": {
            "_": "Weak",
            "duration": "2"
          }
        }
      ]
    },`

2nd occurence:
`{
      "type": "0x212f",
      "id": "Troll 3 Attack 1",
      "Class": "Projectile",
      "Texture": {
        "File": "lofiObj3",
        "Index": "0x2f1"
      }
    },`

Good luck with your exams,
iremnant

**Comment by iremnant** [comment] 2020-05-01 20:40
I'm looking into it and the resource manager is definitely processing different items and objects such as the Staff of the Cosmic Whole.
![image](https://user-images.githubusercontent.com/64452551/80839939-bea0b500-8beb-11ea-8136-4b5b1be5fd50.png)
I believe at least for a temporary fix, adding a simple if statement that checks if the object is already in the map will fix these issues. I will look into it a bit more and send a pull request if I figure it out.

**Closed** 2020-05-02 07:25 UTC
